### ISSUE TITLE
can not fetch user model with async obj = await One.objects.select_related().afirst()

### ISSUE THREAD

**Issue by azataiot** [azataiot/dj-ninja#1]
Model:
```python
class One(models.Model):
    uid = models.UUIDField(
        default=uuid.uuid4,
        editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=16, help_text="Slug of One, (ASCII only)")
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        verbose_name = 'One'
        verbose_name_plural = verbose_name

    def __str__(self):
        return "One: " + str(self.uid)
```

Schema
```python
from ninja.orm import create_schema
from ninja_demo.models import One, Two

OneSchema = create_schema(One, depth=0)
TwoSchema = create_schema(Two, depth=0)

OneSchemaDeep = create_schema(One, depth=1)
TwoSchemaDeep = create_schema(Two, depth=1)
```

Router
``` python

# This is working
@router.get("/async/two/first/deep", response={
    200: TwoSchemaDeep
})
async def async_get_two_first_deep(request):
    obj = await Two.objects.select_related().afirst()
    return obj


# Similar but this is not working
@router.get("/async/one/first/deep", response={
    200: OneSchemaDeep
})
async def async_get_one_first_deep(request):
    obj = await One.objects.select_related().afirst()
    print(obj)
    print(obj.__dict__)
    return obj
```

**Comment by azataiot** [comment]
To tes that this might be Django User (Django Auth) Problem, I decided to create an async endpoint for the User Model.

**Comment by azataiot** [comment]
error: 
```bash
You cannot call this from an async context - use a thread or sync_to_async.
Traceback (most recent call last):
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/operation.py", line 260, in run
    return self._result_to_response(request, result, temporal_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/operation.py", line 196, in _result_to_response
    result = response_model.from_orm(resp_object).dict(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/schema.py", line 164, in from_orm
    return super().from_orm(obj)
           ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 578, in pydantic.main.BaseModel.from_orm
  File "pydantic/main.py", line 1077, in pydantic.main.validate_model
  File "pydantic/fields.py", line 895, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 928, in pydantic.fields.ModelField._validate_sequence_like
  File "pydantic/fields.py", line 1094, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1101, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1148, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 318, in pydantic.class_validators._generic_validator_basic.lambda13
  File "pydantic/main.py", line 714, in pydantic.main.BaseModel.validate
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/schema.py", line 164, in from_orm
    return super().from_orm(obj)
           ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 578, in pydantic.main.BaseModel.from_orm
  File "pydantic/main.py", line 1056, in pydantic.main.validate_model
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/schema.py", line 67, in get
    return self[key]
           ~~~~^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/schema.py", line 63, in __getitem__
    return self._convert_result(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/schema.py", line 73, in _convert_result
    return list(result.all())
           ^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/django/db/models/query.py", line 394, in __iter__
    self._fetch_all()
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 24, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
Internal Server Error: /async/users

```

**Comment by azataiot** [comment]
Considering that this might be a problem on `create_schema` so I might need to create the Schema manually and test it again:

**Comment by azataiot** [comment]
Here is the manually setup Schema for User Model:
``` python
from datetime import datetime
from ninja import Schema
from django.contrib.auth.models import User


class UserSchemaManually(Schema):
    id: int
    username: str
    first_name: str
    last_name: str
    password: str
    last_login: datetime
    is_superuser: bool
    email: str
```

**Comment by azataiot** [comment]
To compare, another schema with `create_schema`
```python
UserSchema = create_schema(User, depth=0)
```

**Comment by azataiot** [comment]
Different Endpoints for the two different schemas:
``` python
@router.get("/async/users", response={
    200: List[UserSchema]
})
async def async_get_users(request):
    objs = []
    async for each in User.objects.select_related().all():
        objs.append(each)
    first = objs[0]
    print(first)
    print(first.__dict__)
    return objs


@router.get("/async/users/manually", response={
    200: List[UserSchemaManually]
})
async def async_get_users_manually(request):
    objs = []
    async for each in User.objects.select_related().all():
        objs.append(each)
    first = objs[0]
    print(first)
    print(first.__dict__)
    return objs
```

**Comment by azataiot** [comment]
for the endpoint with `create_schema`, error details:
``` 
curl -X 'GET' \
  'http://127.0.0.1:8000/async/users' \
  -H 'accept: application/json'
```


```
Traceback (most recent call last):
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/operation.py", line 260, in run
    return self._result_to_response(request, result, temporal_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/operation.py", line 196, in _result_to_response
    result = response_model.from_orm(resp_object).dict(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/schema.py", line 164, in from_orm
    return super().from_orm(obj)
           ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 578, in pydantic.main.BaseModel.from_orm
  File "pydantic/main.py", line 1077, in pydantic.main.validate_model
  File "pydantic/fields.py", line 895, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 928, in pydantic.fields.ModelField._validate_sequence_like
  File "pydantic/fields.py", line 1094, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1101, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1148, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 318, in pydantic.class_validators._generic_validator_basic.lambda13
  File "pydantic/main.py", line 714, in pydantic.main.BaseModel.validate
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/schema.py", line 164, in from_orm
    return super().from_orm(obj)
           ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 578, in pydantic.main.BaseModel.from_orm
  File "pydantic/main.py", line 1056, in pydantic.main.validate_model
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/schema.py", line 67, in get
    return self[key]
           ~~~~^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/schema.py", line 63, in __getitem__
    return self._convert_result(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/ninja/schema.py", line 73, in _convert_result
    return list(result.all())
           ^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/django/db/models/query.py", line 394, in __iter__
    self._fetch_all()
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/azat/Developer/Django/dj_ninja/venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 24, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
```

**Comment by azataiot** [comment]
No error occured when running without `create_schema`
